// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rpc/order_service.proto

/*
	Package rpc is a generated protocol buffer package.

	It is generated from these files:
		rpc/order_service.proto
		rpc/events.proto

	It has these top-level messages:
		Order
		Item
		NewItem
		OrderNewRequest
		OrderItemAddRequest
		OrderItemRemoveRequest
		OrderApproveRequest
		OrderRejectRequest
		OrderResponse
		IDRequest
		OrderCreated
		OrderItemAdded
		OrderItemRemoved
		OrderFulfilled
		EventContainer
*/
package rpc

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/gogoproto"

import time "time"

import types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type OrderStatus int32

const (
	OrderStatus_EMPTY    OrderStatus = 0
	OrderStatus_PENDING  OrderStatus = 1
	OrderStatus_APPROVED OrderStatus = 2
	OrderStatus_REJECTED OrderStatus = 3
	OrderStatus_FAILED   OrderStatus = 4
)

var OrderStatus_name = map[int32]string{
	0: "EMPTY",
	1: "PENDING",
	2: "APPROVED",
	3: "REJECTED",
	4: "FAILED",
}
var OrderStatus_value = map[string]int32{
	"EMPTY":    0,
	"PENDING":  1,
	"APPROVED": 2,
	"REJECTED": 3,
	"FAILED":   4,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}
func (OrderStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptorOrderService, []int{0} }

type Order struct {
	ID          string      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Version     int32       `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Name        string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt   time.Time   `protobuf:"bytes,4,opt,name=createdAt,stdtime" json:"createdAt"`
	UpdatedAt   time.Time   `protobuf:"bytes,5,opt,name=updatedAt,stdtime" json:"updatedAt"`
	DeletedAt   *time.Time  `protobuf:"bytes,6,opt,name=deletedAt,stdtime" json:"deletedAt,omitempty"`
	SignedAt    *time.Time  `protobuf:"bytes,7,opt,name=signedAt,stdtime" json:"signedAt,omitempty"`
	SignedBy    string      `protobuf:"bytes,8,opt,name=signedBy,proto3" json:"signedBy,omitempty"`
	FulfilledAt *time.Time  `protobuf:"bytes,9,opt,name=fulfilledAt,stdtime" json:"fulfilledAt,omitempty"`
	FulfilledBy string      `protobuf:"bytes,10,opt,name=fulfilledBy,proto3" json:"fulfilledBy,omitempty"`
	Items       []*Item     `protobuf:"bytes,11,rep,name=items" json:"items,omitempty"`
	Status      OrderStatus `protobuf:"varint,12,opt,name=status,proto3,enum=acme.OrderStatus" json:"status,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptorOrderService, []int{0} }

func (m *Order) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Order) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Order) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *Order) GetUpdatedAt() time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return time.Time{}
}

func (m *Order) GetDeletedAt() *time.Time {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Order) GetSignedAt() *time.Time {
	if m != nil {
		return m.SignedAt
	}
	return nil
}

func (m *Order) GetSignedBy() string {
	if m != nil {
		return m.SignedBy
	}
	return ""
}

func (m *Order) GetFulfilledAt() *time.Time {
	if m != nil {
		return m.FulfilledAt
	}
	return nil
}

func (m *Order) GetFulfilledBy() string {
	if m != nil {
		return m.FulfilledBy
	}
	return ""
}

func (m *Order) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_EMPTY
}

type Item struct {
	ID          string    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SKU         string    `protobuf:"bytes,2,opt,name=SKU,proto3" json:"SKU,omitempty"`
	Description string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AddedAt     time.Time `protobuf:"bytes,4,opt,name=addedAt,stdtime" json:"addedAt"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptorOrderService, []int{1} }

func (m *Item) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Item) GetSKU() string {
	if m != nil {
		return m.SKU
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetAddedAt() time.Time {
	if m != nil {
		return m.AddedAt
	}
	return time.Time{}
}

type NewItem struct {
	SKU         string `protobuf:"bytes,1,opt,name=SKU,proto3" json:"SKU,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *NewItem) Reset()                    { *m = NewItem{} }
func (m *NewItem) String() string            { return proto.CompactTextString(m) }
func (*NewItem) ProtoMessage()               {}
func (*NewItem) Descriptor() ([]byte, []int) { return fileDescriptorOrderService, []int{2} }

func (m *NewItem) GetSKU() string {
	if m != nil {
		return m.SKU
	}
	return ""
}

func (m *NewItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type OrderNewRequest struct {
	Items []*NewItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *OrderNewRequest) Reset()                    { *m = OrderNewRequest{} }
func (m *OrderNewRequest) String() string            { return proto.CompactTextString(m) }
func (*OrderNewRequest) ProtoMessage()               {}
func (*OrderNewRequest) Descriptor() ([]byte, []int) { return fileDescriptorOrderService, []int{3} }

func (m *OrderNewRequest) GetItems() []*NewItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type OrderItemAddRequest struct {
	OrderID string `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	Item    *Item  `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
}

func (m *OrderItemAddRequest) Reset()                    { *m = OrderItemAddRequest{} }
func (m *OrderItemAddRequest) String() string            { return proto.CompactTextString(m) }
func (*OrderItemAddRequest) ProtoMessage()               {}
func (*OrderItemAddRequest) Descriptor() ([]byte, []int) { return fileDescriptorOrderService, []int{4} }

func (m *OrderItemAddRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *OrderItemAddRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type OrderItemRemoveRequest struct {
	OrderID string `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	ItemID  string `protobuf:"bytes,2,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
}

func (m *OrderItemRemoveRequest) Reset()         { *m = OrderItemRemoveRequest{} }
func (m *OrderItemRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*OrderItemRemoveRequest) ProtoMessage()    {}
func (*OrderItemRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorOrderService, []int{5}
}

func (m *OrderItemRemoveRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *OrderItemRemoveRequest) GetItemID() string {
	if m != nil {
		return m.ItemID
	}
	return ""
}

type OrderApproveRequest struct {
	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FulfilledBy string `protobuf:"bytes,2,opt,name=fulfilledBy,proto3" json:"fulfilledBy,omitempty"`
}

func (m *OrderApproveRequest) Reset()                    { *m = OrderApproveRequest{} }
func (m *OrderApproveRequest) String() string            { return proto.CompactTextString(m) }
func (*OrderApproveRequest) ProtoMessage()               {}
func (*OrderApproveRequest) Descriptor() ([]byte, []int) { return fileDescriptorOrderService, []int{6} }

func (m *OrderApproveRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *OrderApproveRequest) GetFulfilledBy() string {
	if m != nil {
		return m.FulfilledBy
	}
	return ""
}

type OrderRejectRequest struct {
	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FulfilledBy string `protobuf:"bytes,2,opt,name=fulfilledBy,proto3" json:"fulfilledBy,omitempty"`
}

func (m *OrderRejectRequest) Reset()                    { *m = OrderRejectRequest{} }
func (m *OrderRejectRequest) String() string            { return proto.CompactTextString(m) }
func (*OrderRejectRequest) ProtoMessage()               {}
func (*OrderRejectRequest) Descriptor() ([]byte, []int) { return fileDescriptorOrderService, []int{7} }

func (m *OrderRejectRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *OrderRejectRequest) GetFulfilledBy() string {
	if m != nil {
		return m.FulfilledBy
	}
	return ""
}

type OrderResponse struct {
	Order *Order `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
}

func (m *OrderResponse) Reset()                    { *m = OrderResponse{} }
func (m *OrderResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()               {}
func (*OrderResponse) Descriptor() ([]byte, []int) { return fileDescriptorOrderService, []int{8} }

func (m *OrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type IDRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (m *IDRequest) Reset()                    { *m = IDRequest{} }
func (m *IDRequest) String() string            { return proto.CompactTextString(m) }
func (*IDRequest) ProtoMessage()               {}
func (*IDRequest) Descriptor() ([]byte, []int) { return fileDescriptorOrderService, []int{9} }

func (m *IDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "acme.Order")
	proto.RegisterType((*Item)(nil), "acme.Item")
	proto.RegisterType((*NewItem)(nil), "acme.NewItem")
	proto.RegisterType((*OrderNewRequest)(nil), "acme.OrderNewRequest")
	proto.RegisterType((*OrderItemAddRequest)(nil), "acme.OrderItemAddRequest")
	proto.RegisterType((*OrderItemRemoveRequest)(nil), "acme.OrderItemRemoveRequest")
	proto.RegisterType((*OrderApproveRequest)(nil), "acme.OrderApproveRequest")
	proto.RegisterType((*OrderRejectRequest)(nil), "acme.OrderRejectRequest")
	proto.RegisterType((*OrderResponse)(nil), "acme.OrderResponse")
	proto.RegisterType((*IDRequest)(nil), "acme.IDRequest")
	proto.RegisterEnum("acme.OrderStatus", OrderStatus_name, OrderStatus_value)
}
func (m *Order) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Order) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if m.Version != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(m.Version))
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	dAtA[i] = 0x22
	i++
	i = encodeVarintOrderService(dAtA, i, uint64(types.SizeOfStdTime(m.CreatedAt)))
	n1, err := types.StdTimeMarshalTo(m.CreatedAt, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x2a
	i++
	i = encodeVarintOrderService(dAtA, i, uint64(types.SizeOfStdTime(m.UpdatedAt)))
	n2, err := types.StdTimeMarshalTo(m.UpdatedAt, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if m.DeletedAt != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(types.SizeOfStdTime(*m.DeletedAt)))
		n3, err := types.StdTimeMarshalTo(*m.DeletedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.SignedAt != nil {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(types.SizeOfStdTime(*m.SignedAt)))
		n4, err := types.StdTimeMarshalTo(*m.SignedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if len(m.SignedBy) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.SignedBy)))
		i += copy(dAtA[i:], m.SignedBy)
	}
	if m.FulfilledAt != nil {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(types.SizeOfStdTime(*m.FulfilledAt)))
		n5, err := types.StdTimeMarshalTo(*m.FulfilledAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if len(m.FulfilledBy) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.FulfilledBy)))
		i += copy(dAtA[i:], m.FulfilledBy)
	}
	if len(m.Items) > 0 {
		for _, msg := range m.Items {
			dAtA[i] = 0x5a
			i++
			i = encodeVarintOrderService(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Status != 0 {
		dAtA[i] = 0x60
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(m.Status))
	}
	return i, nil
}

func (m *Item) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Item) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.SKU) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.SKU)))
		i += copy(dAtA[i:], m.SKU)
	}
	if len(m.Description) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.Description)))
		i += copy(dAtA[i:], m.Description)
	}
	dAtA[i] = 0x22
	i++
	i = encodeVarintOrderService(dAtA, i, uint64(types.SizeOfStdTime(m.AddedAt)))
	n6, err := types.StdTimeMarshalTo(m.AddedAt, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n6
	return i, nil
}

func (m *NewItem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NewItem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.SKU) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.SKU)))
		i += copy(dAtA[i:], m.SKU)
	}
	if len(m.Description) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.Description)))
		i += copy(dAtA[i:], m.Description)
	}
	return i, nil
}

func (m *OrderNewRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderNewRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for _, msg := range m.Items {
			dAtA[i] = 0x12
			i++
			i = encodeVarintOrderService(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *OrderItemAddRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderItemAddRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.OrderID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.OrderID)))
		i += copy(dAtA[i:], m.OrderID)
	}
	if m.Item != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(m.Item.Size()))
		n7, err := m.Item.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}

func (m *OrderItemRemoveRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderItemRemoveRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.OrderID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.OrderID)))
		i += copy(dAtA[i:], m.OrderID)
	}
	if len(m.ItemID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.ItemID)))
		i += copy(dAtA[i:], m.ItemID)
	}
	return i, nil
}

func (m *OrderApproveRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderApproveRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.FulfilledBy) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.FulfilledBy)))
		i += copy(dAtA[i:], m.FulfilledBy)
	}
	return i, nil
}

func (m *OrderRejectRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderRejectRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.FulfilledBy) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.FulfilledBy)))
		i += copy(dAtA[i:], m.FulfilledBy)
	}
	return i, nil
}

func (m *OrderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Order != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(m.Order.Size()))
		n8, err := m.Order.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	return i, nil
}

func (m *IDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IDRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOrderService(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	return i, nil
}

func encodeVarintOrderService(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Order) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovOrderService(uint64(m.Version))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	l = types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovOrderService(uint64(l))
	l = types.SizeOfStdTime(m.UpdatedAt)
	n += 1 + l + sovOrderService(uint64(l))
	if m.DeletedAt != nil {
		l = types.SizeOfStdTime(*m.DeletedAt)
		n += 1 + l + sovOrderService(uint64(l))
	}
	if m.SignedAt != nil {
		l = types.SizeOfStdTime(*m.SignedAt)
		n += 1 + l + sovOrderService(uint64(l))
	}
	l = len(m.SignedBy)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	if m.FulfilledAt != nil {
		l = types.SizeOfStdTime(*m.FulfilledAt)
		n += 1 + l + sovOrderService(uint64(l))
	}
	l = len(m.FulfilledBy)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovOrderService(uint64(l))
		}
	}
	if m.Status != 0 {
		n += 1 + sovOrderService(uint64(m.Status))
	}
	return n
}

func (m *Item) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	l = len(m.SKU)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	l = types.SizeOfStdTime(m.AddedAt)
	n += 1 + l + sovOrderService(uint64(l))
	return n
}

func (m *NewItem) Size() (n int) {
	var l int
	_ = l
	l = len(m.SKU)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	return n
}

func (m *OrderNewRequest) Size() (n int) {
	var l int
	_ = l
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovOrderService(uint64(l))
		}
	}
	return n
}

func (m *OrderItemAddRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.OrderID)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	if m.Item != nil {
		l = m.Item.Size()
		n += 1 + l + sovOrderService(uint64(l))
	}
	return n
}

func (m *OrderItemRemoveRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.OrderID)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	l = len(m.ItemID)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	return n
}

func (m *OrderApproveRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	l = len(m.FulfilledBy)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	return n
}

func (m *OrderRejectRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	l = len(m.FulfilledBy)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	return n
}

func (m *OrderResponse) Size() (n int) {
	var l int
	_ = l
	if m.Order != nil {
		l = m.Order.Size()
		n += 1 + l + sovOrderService(uint64(l))
	}
	return n
}

func (m *IDRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovOrderService(uint64(l))
	}
	return n
}

func sovOrderService(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozOrderService(x uint64) (n int) {
	return sovOrderService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Order) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Order: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Order: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := types.StdTimeUnmarshal(&m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedAt == nil {
				m.DeletedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.DeletedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SignedAt == nil {
				m.SignedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.SignedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FulfilledAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FulfilledAt == nil {
				m.FulfilledAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.FulfilledAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FulfilledBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FulfilledBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, &Item{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (OrderStatus(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrderService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrderService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Item) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Item: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Item: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SKU", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SKU = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := types.StdTimeUnmarshal(&m.AddedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrderService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrderService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NewItem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NewItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NewItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SKU", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SKU = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrderService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrderService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderNewRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderNewRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderNewRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, &NewItem{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrderService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrderService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderItemAddRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderItemAddRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderItemAddRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Item", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Item == nil {
				m.Item = &Item{}
			}
			if err := m.Item.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrderService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrderService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderItemRemoveRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderItemRemoveRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderItemRemoveRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ItemID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrderService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrderService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderApproveRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderApproveRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderApproveRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FulfilledBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FulfilledBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrderService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrderService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderRejectRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderRejectRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderRejectRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FulfilledBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FulfilledBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrderService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrderService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Order == nil {
				m.Order = &Order{}
			}
			if err := m.Order.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrderService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrderService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOrderService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrderService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOrderService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOrderService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOrderService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrderService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthOrderService
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowOrderService
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipOrderService(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthOrderService = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOrderService   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("rpc/order_service.proto", fileDescriptorOrderService) }

var fileDescriptorOrderService = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xc1, 0x4e, 0xdb, 0x4a,
	0x14, 0x86, 0xb1, 0xe3, 0xc4, 0xf1, 0x71, 0x80, 0x30, 0xe8, 0x72, 0x7d, 0x73, 0xab, 0xe0, 0xba,
	0x9b, 0xb4, 0x52, 0x9d, 0x2a, 0x95, 0x2a, 0x21, 0x51, 0xaa, 0x04, 0x1b, 0x64, 0x5a, 0x42, 0x64,
	0x68, 0xa5, 0x76, 0x53, 0x05, 0x7b, 0x48, 0x5d, 0xc5, 0xb1, 0x6b, 0x4f, 0x40, 0xbc, 0x42, 0x57,
	0x5d, 0xf7, 0x89, 0x58, 0xf6, 0x09, 0xda, 0x8a, 0x77, 0xe8, 0xbe, 0xf2, 0x8c, 0x1d, 0x1c, 0x08,
	0x05, 0xba, 0xf3, 0x99, 0x39, 0xdf, 0x7f, 0xce, 0x9c, 0xf9, 0x3d, 0xf0, 0x6f, 0x14, 0x3a, 0xcd,
	0x20, 0x72, 0x71, 0xf4, 0x3e, 0xc6, 0xd1, 0xb1, 0xe7, 0x60, 0x3d, 0x8c, 0x02, 0x12, 0x20, 0xa1,
	0xef, 0xf8, 0xb8, 0xb6, 0x3a, 0x08, 0x82, 0xc1, 0x10, 0x37, 0xe9, 0xda, 0xe1, 0xf8, 0xa8, 0x49,
	0x3c, 0x1f, 0xc7, 0xa4, 0xef, 0x87, 0x2c, 0xad, 0xf6, 0x78, 0xe0, 0x91, 0x0f, 0xe3, 0x43, 0xdd,
	0x09, 0xfc, 0xe6, 0x20, 0x18, 0x04, 0x17, 0x99, 0x49, 0x44, 0x03, 0xfa, 0xc5, 0xd2, 0xb5, 0xaf,
	0x02, 0x14, 0xf7, 0x92, 0x6a, 0x68, 0x01, 0x78, 0xcb, 0x50, 0x38, 0x95, 0x6b, 0x48, 0x36, 0x6f,
	0x19, 0x48, 0x01, 0xf1, 0x18, 0x47, 0xb1, 0x17, 0x8c, 0x14, 0x5e, 0xe5, 0x1a, 0x45, 0x3b, 0x0b,
	0x11, 0x02, 0x61, 0xd4, 0xf7, 0xb1, 0x52, 0xa0, 0xb9, 0xf4, 0x1b, 0x75, 0x40, 0x72, 0x22, 0xdc,
	0x27, 0xd8, 0x6d, 0x13, 0x45, 0x50, 0xb9, 0x86, 0xdc, 0xaa, 0xe9, 0xac, 0x57, 0x3d, 0xeb, 0x40,
	0x3f, 0xc8, 0x7a, 0xed, 0x94, 0xcf, 0xbe, 0xaf, 0xce, 0x7d, 0xf9, 0xb1, 0xca, 0xd9, 0x17, 0x58,
	0xa2, 0x31, 0x0e, 0xdd, 0x54, 0xa3, 0x78, 0x17, 0x8d, 0x09, 0x86, 0x36, 0x40, 0x72, 0xf1, 0x10,
	0x33, 0x8d, 0xd2, 0x8d, 0x1a, 0x02, 0xe3, 0x27, 0x08, 0x5a, 0x87, 0x72, 0xec, 0x0d, 0x46, 0x14,
	0x17, 0x6f, 0x89, 0x4f, 0x08, 0x54, 0xcb, 0xe8, 0xce, 0xa9, 0x52, 0xa6, 0xd3, 0x99, 0xc4, 0xa8,
	0x03, 0xf2, 0xd1, 0x78, 0x78, 0xe4, 0x0d, 0x87, 0x54, 0x5c, 0xba, 0xa5, 0x78, 0x1e, 0x42, 0x6a,
	0x4e, 0xa3, 0x73, 0xaa, 0x00, 0x2d, 0x91, 0x5f, 0x42, 0x2a, 0x14, 0x3d, 0x82, 0xfd, 0x58, 0x91,
	0xd5, 0x42, 0x43, 0x6e, 0x81, 0x9e, 0xb8, 0x46, 0xb7, 0x08, 0xf6, 0x6d, 0xb6, 0x81, 0x1e, 0x42,
	0x29, 0x26, 0x7d, 0x32, 0x8e, 0x95, 0x8a, 0xca, 0x35, 0x16, 0x5a, 0x4b, 0x2c, 0x85, 0x9a, 0x60,
	0x9f, 0x6e, 0xd8, 0x69, 0x82, 0xf6, 0x99, 0x03, 0x21, 0x41, 0xaf, 0x78, 0xa3, 0x0a, 0x85, 0xfd,
	0x97, 0xaf, 0xa9, 0x2f, 0x24, 0x3b, 0xf9, 0x4c, 0x3a, 0x73, 0x71, 0xec, 0x44, 0x5e, 0x48, 0x12,
	0xc7, 0x30, 0x6b, 0xe4, 0x97, 0xd0, 0x06, 0x88, 0x7d, 0xd7, 0xbd, 0xb3, 0x3f, 0x32, 0x48, 0x7b,
	0x0e, 0x62, 0x17, 0x9f, 0xd0, 0x76, 0xd2, 0xf2, 0xdc, 0xb5, 0xe5, 0xf9, 0x2b, 0xe5, 0xb5, 0x67,
	0xb0, 0x48, 0x8f, 0xd8, 0xc5, 0x27, 0x36, 0xfe, 0x34, 0xc6, 0x31, 0x41, 0x0f, 0xb2, 0x59, 0xf1,
	0x74, 0x56, 0xf3, 0x6c, 0x10, 0x69, 0x91, 0x74, 0x5c, 0xda, 0x1e, 0x2c, 0x53, 0x2e, 0x59, 0x6b,
	0xbb, 0x6e, 0xc6, 0x2a, 0x20, 0xb2, 0xe5, 0x6c, 0x2c, 0x59, 0x88, 0xea, 0x20, 0x24, 0x24, 0xed,
	0x61, 0xfa, 0x02, 0xe8, 0xba, 0xb6, 0x03, 0x2b, 0x13, 0x41, 0x1b, 0xfb, 0xc1, 0x31, 0xbe, 0x59,
	0x73, 0x05, 0x4a, 0x49, 0xba, 0x65, 0xa4, 0x27, 0x4b, 0x23, 0x6d, 0x3b, 0x6d, 0xae, 0x1d, 0x86,
	0x51, 0x4e, 0xe8, 0xf2, 0x75, 0x5d, 0xb2, 0x0d, 0x7f, 0xc5, 0x36, 0xda, 0x16, 0x20, 0x2a, 0x64,
	0xe3, 0x8f, 0xd8, 0x21, 0x7f, 0xaf, 0xd3, 0x82, 0xf9, 0x54, 0x27, 0x0e, 0x83, 0x51, 0x8c, 0xd1,
	0x7d, 0x28, 0xd2, 0xc7, 0x8c, 0xaa, 0xc8, 0x2d, 0x39, 0x67, 0x36, 0x9b, 0xed, 0x68, 0xff, 0x83,
	0x64, 0x19, 0xd7, 0x94, 0x7c, 0xb4, 0x0b, 0x72, 0xce, 0x99, 0x48, 0x82, 0xa2, 0xb9, 0xdb, 0x3b,
	0x78, 0x5b, 0x9d, 0x43, 0x32, 0x88, 0x3d, 0xb3, 0x6b, 0x58, 0xdd, 0xed, 0x2a, 0x87, 0x2a, 0x50,
	0x6e, 0xf7, 0x7a, 0xf6, 0xde, 0x1b, 0xd3, 0xa8, 0xf2, 0x49, 0x64, 0x9b, 0x3b, 0xe6, 0xe6, 0x81,
	0x69, 0x54, 0x0b, 0x08, 0xa0, 0xb4, 0xd5, 0xb6, 0x5e, 0x99, 0x46, 0x55, 0x68, 0xfd, 0xe2, 0xa1,
	0xc2, 0xf4, 0xd8, 0xdb, 0x8a, 0xd6, 0x40, 0xde, 0xa4, 0x0f, 0x10, 0x7b, 0x04, 0xff, 0xc9, 0xf5,
	0x77, 0xe1, 0x94, 0xda, 0x72, 0xbe, 0xed, 0xec, 0x68, 0x6b, 0x20, 0xb6, 0x5d, 0x97, 0x1a, 0xf2,
	0xbf, 0xdc, 0xfe, 0xb4, 0x51, 0x66, 0xa3, 0x2f, 0x00, 0xd8, 0xd5, 0x53, 0xfa, 0xde, 0x25, 0x7a,
	0xca, 0x15, 0xb3, 0x05, 0x36, 0xa0, 0x92, 0xde, 0x39, 0xeb, 0x3b, 0xdf, 0xc0, 0xb4, 0x19, 0x66,
	0xf3, 0xeb, 0x20, 0xb3, 0xab, 0x66, 0xb8, 0x32, 0x95, 0x93, 0xb3, 0xc0, 0x6c, 0xfa, 0x09, 0x94,
	0xb7, 0x71, 0x8a, 0x2e, 0xa6, 0x06, 0x37, 0xfe, 0x44, 0x74, 0x96, 0xce, 0xce, 0xeb, 0xdc, 0xb7,
	0xf3, 0x3a, 0xf7, 0xf3, 0xbc, 0xce, 0xbd, 0x2b, 0x44, 0xa1, 0x73, 0x58, 0xa2, 0xbf, 0xfd, 0xd3,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x77, 0x90, 0x2d, 0xf1, 0x06, 0x00, 0x00,
}
